export const GET_BLOCKED_WORDS_REQUEST = 'GET_BLOCKED_WORDS_REQUEST';
export const GET_BLOCKED_WORDS_SUCCESS = 'GET_BLOCKED_WORDS_SUCCESS';
export const GET_BLOCKED_WORDS_ERROR   = 'GET_BLOCKED_WORDS_ERROR';

export const INSERT_BLOCK_WORD_REQUEST = 'INSERT_BLOCK_WORD_REQUEST';
export const INSERT_BLOCK_WORD_SUCCESS = 'INSERT_BLOCK_WORD_SUCCESS';
export const INSERT_BLOCK_WORD_ERROR   = 'INSERT_BLOCK_WORD_ERROR';

export const REMOVE_BLOCK_WORD_REQUEST = 'REMOVE_BLOCK_WORD_REQUEST';
export const REMOVE_BLOCK_WORD_SUCCESS = 'REMOVE_BLOCK_WORD_SUCCESS';
export const REMOVE_BLOCK_WORD_ERROR   = 'REMOVE_BLOCK_WORD_ERROR';

export const GET_VIDEOS_REQUEST = 'GET_VIDEOS_REQUEST';
export const GET_VIDEOS_SUCCESS = 'GET_VIDEOS_SUCCESS';
export const GET_VIDEOS_ERROR   = 'GET_VIDEOS_ERROR';

export const INSERT_VIDEO_REQUEST = 'INSERT_VIDEO_REQUEST';
export const INSERT_VIDEO_SUCCESS = 'INSERT_VIDEO_SUCCESS';
export const INSERT_VIDEO_ERROR   = 'INSERT_VIDEO_ERROR';

export const UPDATE_VIDEO   = 'UPDATE_VIDEO';

