const GET_ALL_BLOCKED_WORDS_REQUEST = 'GET_BLOCKED_WORDS_REQUEST';
const GET_ALL_BLOCKED_WORDS_SUCCESS = 'GET_BLOCKED_WORDS_SUCCESS';
const GET_ALL_BLOCKED_WORDS_ERROR = 'GET_BLOCKED_WORDS_ERROR';

const INSERT_BLOCK_WORD_REQUEST = 'INSERT_BLOCK_WORD_REQUEST';
const INSERT_BLOCK_WORD_SUCCESS = 'INSERT_BLOCK_WORD_SUCCESS';
const INSERT_BLOCK_WORD_ERROR = 'INSERT_BLOCK_WORD_ERROR';

const REMOVE_BLOCK_WORD_REQUEST = 'REMOVE_BLOCK_WORD_REQUEST';
const REMOVE_BLOCK_WORD_SUCCESS = 'REMOVE_BLOCK_WORD_SUCCESS';
const REMOVE_BLOCK_WORD_ERROR = 'REMOVE_BLOCK_WORD_ERROR';

